using System.Windows;
using Syncfusion.SfSkinManager; // Theme manager
using Syncfusion.Windows.Shared; // Theme names (if needed)
using Syncfusion.UI.Xaml.Grid; // Grid controls
using Syncfusion.Windows.Tools.Controls; // Ribbon controls
using WileyWidget.Services;
using Serilog;
using System.Linq;
using Microsoft.Extensions.DependencyInjection;

namespace WileyWidget;

/// <summary>
/// Primary shell window: applies persisted theme + window geometry, wires basic commands (theme switch, about),
/// and persists size/state on close. Keeps logic minimal—heavy operations belong in view models/services.
/// </summary>
public partial class MainWindow : Window
{
    // Runtime toggle for dynamic column generation (kept non-const to avoid CS0162 unreachable warning when false).
    private static readonly bool UseDynamicColumns = true; // set true to enable runtime column build

    // Grid control field (automatically generated by WPF from XAML x:Name)
    // private Syncfusion.UI.Xaml.Grid.SfDataGrid Grid;

    // Ribbon button fields (automatically generated by WPF from XAML x:Name)
    // private dynamic BtnFluentDark;
    // private dynamic BtnFluentLight;
    // private dynamic BtnDynamicColumns;

    private readonly AuthenticationService _authService;
    private readonly IServiceProvider _serviceProvider;
    private IServiceScope _viewScope; // keep scoped services alive for the window lifetime

    private Syncfusion.UI.Xaml.Grid.SfDataGrid GetDataGrid()
    {
        return FindName("Grid") as Syncfusion.UI.Xaml.Grid.SfDataGrid;
    }

    public MainWindow()
    {
        InitializeComponent();

        try
        {
            var provider = App.ServiceProvider;
            if (provider == null && Application.Current?.Properties?.Contains("ServiceProvider") == true)
            {
                provider = Application.Current.Properties["ServiceProvider"] as System.IServiceProvider;
            }
            if (provider == null)
                throw new System.InvalidOperationException("ServiceProvider is not initialized. Ensure DI container is built in App.OnStartup before creating MainWindow.");

            // Store the provider for later use when creating scoped services
            _serviceProvider = provider;

            // Get authentication service (singleton, safe to resolve from root)
            _authService = provider.GetRequiredService<AuthenticationService>();
            _authService.AuthenticationStateChanged += OnAuthenticationStateChanged;
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to initialize MainWindow services");
            MessageBox.Show($"Failed to initialize application: {ex.Message}", "Initialization Error", MessageBoxButton.OK, MessageBoxImage.Error);
            Application.Current.Shutdown();
        }

        // Apply persisted theme or default
        TryApplyTheme(SettingsService.Instance.Current.Theme);
        if (UseDynamicColumns)
            BuildDynamicColumns();
        RestoreWindowState();
        Loaded += OnWindowLoaded;
        Closing += (_, _) => PersistWindowState();
        UpdateThemeToggleVisuals();
    }

    private void OnWindowLoaded(object sender, RoutedEventArgs e)
    {
        // Initialize DataContext with scoped services when window is loaded
        try
        {
            _viewScope = _serviceProvider.CreateScope();
            DataContext = _viewScope.ServiceProvider.GetRequiredService<ViewModels.MainViewModel>();

            // Now that DataContext and visual tree are ready, apply maximized state and auth UI
            ApplyMaximized();
            UpdateAuthenticationUI();
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to initialize MainViewModel");
            MessageBox.Show($"Failed to initialize main view: {ex.Message}", "Initialization Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }

        // Dispose scope and unsubscribe events when the window is closing
        this.Closing += (_, _) =>
        {
            try
            {
                _authService.AuthenticationStateChanged -= OnAuthenticationStateChanged;
            }
            catch { /* ignore */ }
            try
            {
                _viewScope?.Dispose();
                _viewScope = null;
            }
            catch { /* ignore */ }
        };
    }

    /// <summary>
    /// Dynamically builds columns for each public property of the widget model when enabled.
    /// Supports different column types based on property types and includes proper formatting.
    /// </summary>
    private void BuildDynamicColumns()
    {
        try
        {
            var vm = DataContext as ViewModels.MainViewModel;
            var items = vm?.Enterprises;
            if (items == null || items.Count == 0) return;

            var grid = GetDataGrid();
            if (grid == null) return;
            grid.AutoGenerateColumns = false;
            grid.Columns.Clear();

            var type = items[0].GetType();
            foreach (var prop in type.GetProperties())
            {
                if (!prop.CanRead) continue;

                var mappingName = prop.Name;
                var headerText = SplitCamelCase(prop.Name);

                // Create appropriate column type based on property type
                var column = CreateColumnForProperty(prop, mappingName, headerText);
                if (column != null)
                {
                    grid.Columns.Add(column);
                }
            }

            Log.Information("Dynamic columns built successfully for {TypeName}", type.Name);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to build dynamic columns");
            // Fallback to basic auto-generated columns
            var grid = GetDataGrid();
            if (grid != null) grid.AutoGenerateColumns = true;
        }
    }

    /// <summary>
    /// Creates the appropriate Syncfusion column type based on the property type
    /// </summary>
    private Syncfusion.UI.Xaml.Grid.GridColumn CreateColumnForProperty(System.Reflection.PropertyInfo prop, string mappingName, string headerText)
    {
        var propType = prop.PropertyType;

        // Handle nullable types
        var underlyingType = Nullable.GetUnderlyingType(propType) ?? propType;

        if (underlyingType == typeof(int) || underlyingType == typeof(long) ||
            underlyingType == typeof(short) || underlyingType == typeof(byte))
        {
            return new GridNumericColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                NumberDecimalDigits = 0,
                Width = 100
            };
        }
        else if (underlyingType == typeof(decimal) || underlyingType == typeof(double) ||
                 underlyingType == typeof(float))
        {
            return new GridNumericColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                NumberDecimalDigits = 2,
                Width = 120
            };
        }
        else if (underlyingType == typeof(DateTime))
        {
            return new GridDateTimeColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = 140
            };
        }
        else if (underlyingType == typeof(bool))
        {
            return new GridCheckBoxColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = 80
            };
        }
        else
        {
            // Default to text column for strings and other types
            return new GridTextColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = 150
            };
        }
    }

    /// <summary>
    /// Converts camelCase or PascalCase to readable text with spaces
    /// </summary>
    private string SplitCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;

        var result = System.Text.RegularExpressions.Regex.Replace(input, "([a-z])([A-Z])", "$1 $2");
        return result;
    }

    /// <summary>
    /// Copy selected items from the data grid to clipboard
    /// </summary>
    private void OnCopy(object sender, RoutedEventArgs e)
    {
        try
        {
            var grid = GetDataGrid();
            if (grid == null || grid.SelectedItems == null || grid.SelectedItems.Count == 0)
            {
                MessageBox.Show("Please select one or more items to copy.",
                              "No Selection",
                              MessageBoxButton.OK,
                              MessageBoxImage.Information);
                return;
            }

            var selectedItems = grid.SelectedItems;
            var stringBuilder = new System.Text.StringBuilder();

            // Add header row
            if (selectedItems.Count > 0 && selectedItems[0] != null)
            {
                var type = selectedItems[0].GetType();
                var properties = type.GetProperties()
                    .Where(p => p.CanRead)
                    .Select(p => SplitCamelCase(p.Name))
                    .ToArray();

                stringBuilder.AppendLine(string.Join("\t", properties));
            }

            // Add data rows
            foreach (var item in selectedItems)
            {
                if (item == null) continue;

                var type = item.GetType();
                var values = type.GetProperties()
                    .Where(p => p.CanRead)
                    .Select(p =>
                    {
                        try
                        {
                            var value = p.GetValue(item);
                            return value?.ToString() ?? "";
                        }
                        catch
                        {
                            return "";
                        }
                    })
                    .ToArray();

                stringBuilder.AppendLine(string.Join("\t", values));
            }

            Clipboard.SetText(stringBuilder.ToString());
            Log.Information("Copied {Count} items to clipboard", selectedItems.Count);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to copy items to clipboard");
            MessageBox.Show($"Failed to copy items: {ex.Message}",
                          "Copy Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Paste items from clipboard to the data grid
    /// </summary>
    private void OnPaste(object sender, RoutedEventArgs e)
    {
        try
        {
            if (!Clipboard.ContainsText())
            {
                MessageBox.Show("Clipboard does not contain text data.",
                              "No Text Data",
                              MessageBoxButton.OK,
                              MessageBoxImage.Information);
                return;
            }

            var clipboardText = Clipboard.GetText();
            var lines = clipboardText.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.RemoveEmptyEntries);

            if (lines.Length < 2) // Need at least header + 1 data row
            {
                MessageBox.Show("Clipboard data must contain headers and at least one data row.",
                              "Invalid Format",
                              MessageBoxButton.OK,
                              MessageBoxImage.Warning);
                return;
            }

            var vm = DataContext as ViewModels.MainViewModel;
            if (vm == null) return;

            // Parse header to understand column mapping
            var headers = lines[0].Split('\t').Select(h => h.Trim()).ToArray();

            // Create new items from data rows
            for (int i = 1; i < lines.Length; i++)
            {
                var values = lines[i].Split('\t').Select(v => v.Trim()).ToArray();
                if (values.Length != headers.Length) continue;

                try
                {
                    vm.AddEnterpriseCommand.Execute(null); // This will add a new enterprise
                }
                catch (Exception ex)
                {
                    Log.Warning(ex, "Failed to add widget during paste operation");
                }
            }

            Log.Information("Pasted {Count} items from clipboard", lines.Length - 1);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to paste items from clipboard");
            MessageBox.Show($"Failed to paste items: {ex.Message}",
                          "Paste Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Attempt to apply a Syncfusion theme; falls back to Fluent Light if requested theme fails (e.g., renamed or removed).
    /// </summary>
    private void TryApplyTheme(string themeName)
    {
        try
        {
            var canonical = NormalizeTheme(themeName);
#pragma warning disable CA2000 // Dispose objects before losing scope - Theme objects are managed by SfSkinManager
            SfSkinManager.SetTheme(this, new Theme(canonical));
#pragma warning restore CA2000 // Dispose objects before losing scope
        }
        catch
        {
            if (themeName != "FluentLight")
            {
                // Fallback
#pragma warning disable CA2000 // Dispose objects before losing scope - Theme objects are managed by SfSkinManager
                try { SfSkinManager.SetTheme(this, new Theme("FluentLight")); } catch { /* ignore */ }
#pragma warning restore CA2000 // Dispose objects before losing scope
            }
        }
    }

    private string NormalizeTheme(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return "FluentDark";
        raw = raw.Replace(" ", string.Empty); // allow "Fluent Dark" legacy
        return raw switch
        {
            "FluentDark" => "FluentDark",
            "FluentLight" => "FluentLight",
            _ => "FluentDark" // default
        };
    }

    /// <summary>Switch to Fluent Dark theme and persist choice.</summary>
    private void OnFluentDark(object sender, RoutedEventArgs e)
    {
    TryApplyTheme("FluentDark");
    SettingsService.Instance.Current.Theme = "FluentDark";
        SettingsService.Instance.Save();
    Log.Information("Theme changed to {Theme}", "Fluent Dark");
    UpdateThemeToggleVisuals();
    }
    /// <summary>Switch to Fluent Light theme and persist choice.</summary>
    private void OnFluentLight(object sender, RoutedEventArgs e)
    {
    TryApplyTheme("FluentLight");
    SettingsService.Instance.Current.Theme = "FluentLight";
        SettingsService.Instance.Save();
    Log.Information("Theme changed to {Theme}", "Fluent Light");
        UpdateThemeToggleVisuals();
    }

    private void UpdateThemeToggleVisuals()
    {
        var current = NormalizeTheme(SettingsService.Instance.Current.Theme);
        var btnDark = FindName("BtnFluentDark") as RibbonButton;
        if (btnDark != null)
        {
            btnDark.IsEnabled = current != "FluentDark";
            btnDark.Label = current == "FluentDark" ? "✔ Fluent Dark" : "Fluent Dark";
        }
        var btnLight = FindName("BtnFluentLight") as RibbonButton;
        if (btnLight != null)
        {
            btnLight.IsEnabled = current != "FluentLight";
            btnLight.Label = current == "FluentLight" ? "✔ Fluent Light" : "Fluent Light";
        }
    }
    /// <summary>Display modal About dialog with version information.</summary>
    private void OnAbout(object sender, RoutedEventArgs e)
    {
        var about = new AboutWindow { Owner = this };
        about.ShowDialog();
    }

    /// <summary>
    /// Restores last known window bounds (only if previously saved). Maximized state is applied after window is loaded
    /// to avoid layout measurement issues during construction.
    /// </summary>
    private void RestoreWindowState()
    {
        var s = SettingsService.Instance.Current;
        if (s.WindowWidth.HasValue) Width = s.WindowWidth.Value;
        if (s.WindowHeight.HasValue) Height = s.WindowHeight.Value;
        if (s.WindowLeft.HasValue) Left = s.WindowLeft.Value;
        if (s.WindowTop.HasValue) Top = s.WindowTop.Value;
    }

    /// <summary>
    /// Applies persisted maximized state post-load. Separated for clarity and potential future animation hooks.
    /// </summary>
    private void ApplyMaximized()
    {
        var s = SettingsService.Instance.Current;
        if (s.WindowMaximized == true)
            WindowState = WindowState.Maximized;
    }

    /// <summary>
    /// Persists window bounds only when in Normal state to avoid capturing the restored size of a maximized window.
    /// </summary>
    private void PersistWindowState()
    {
        var s = SettingsService.Instance.Current;
        s.WindowMaximized = WindowState == WindowState.Maximized;
        if (WindowState == WindowState.Normal)
        {
            s.WindowWidth = Width;
            s.WindowHeight = Height;
            s.WindowLeft = Left;
            s.WindowTop = Top;
        }
        SettingsService.Instance.Save();
    }

    /// <summary>
    /// Opens the Enterprise Management window
    /// </summary>
    private void OnEnterpriseManagement(object sender, RoutedEventArgs e)
    {
        try
        {
            EnterpriseView.ShowEnterpriseWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Enterprise Management: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Budget Analysis window
    /// </summary>
    private void OnBudgetAnalysis(object sender, RoutedEventArgs e)
    {
        try
        {
            BudgetView.ShowBudgetWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Budget Analysis: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Customer Management window
    /// </summary>
    private void OnCustomerManagement(object sender, RoutedEventArgs e)
    {
        try
        {
            UtilityCustomerView.ShowCustomerWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Customer Management: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Toggles between static and dynamic column generation
    /// </summary>
    private void OnToggleDynamicColumns(object sender, RoutedEventArgs e)
    {
        try
        {
            var grid = GetDataGrid();
            if (grid == null) return;
            if (grid.AutoGenerateColumns)
            {
                // Switch to static columns
                grid.AutoGenerateColumns = false;
                grid.Columns.Clear();

                // Add static columns for enterprises
                grid.Columns.Add(new GridTextColumn { HeaderText = "Id", MappingName = "Id", Width = 60 });
                grid.Columns.Add(new GridTextColumn { HeaderText = "Name", MappingName = "Name", Width = 150 });
                grid.Columns.Add(new GridTextColumn { HeaderText = "Type", MappingName = "Type", Width = 100 });
                grid.Columns.Add(new GridNumericColumn { HeaderText = "Current Rate", MappingName = "CurrentRate", Width = 100 });
                grid.Columns.Add(new GridNumericColumn { HeaderText = "Monthly Expenses", MappingName = "MonthlyExpenses", Width = 130 });
                grid.Columns.Add(new GridNumericColumn { HeaderText = "Citizens Served", MappingName = "CitizenCount", Width = 120 });
                grid.Columns.Add(new GridNumericColumn { HeaderText = "Monthly Revenue", MappingName = "MonthlyRevenue", Width = 130 });
                grid.Columns.Add(new GridNumericColumn { HeaderText = "Monthly Balance", MappingName = "MonthlyBalance", Width = 120 });
                grid.Columns.Add(new GridTextColumn { HeaderText = "Notes", MappingName = "Notes", Width = 200 });

                // BtnDynamicColumns.Label = "Dynamic Columns";
                Log.Information("Switched to static columns");
            }
            else
            {
                // Switch to dynamic columns
                BuildDynamicColumns();
                // BtnDynamicColumns.Label = "Static Columns";
                Log.Information("Switched to dynamic columns");
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to toggle column mode");
            MessageBox.Show($"Failed to toggle column mode: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the AI Assistant window
    /// </summary>
    private void OnAIAssist(object sender, RoutedEventArgs e)
    {
        try
        {
            AIAssistView.ShowAIAssistWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open AI Assistant: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Settings window
    /// </summary>
    private void OnSettings(object sender, RoutedEventArgs e)
    {
        try
        {
            var settingsWindow = new SettingsView
            {
                Owner = this
            };
            settingsWindow.ShowDialog();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Settings: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Dashboard window
    /// </summary>
    private void OnDashboard(object sender, RoutedEventArgs e)
    {
        try
        {
            DashboardView.ShowDashboardWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Dashboard: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Handles keyboard shortcuts by delegating to existing event handlers
    /// </summary>
    private void HandleKeyboardShortcut(string action)
    {
        try
        {
            switch (action)
            {
                case "Settings":
                    OnSettings(null, null);
                    break;
                case "Dashboard":
                    OnDashboard(null, null);
                    break;
                case "AIAssist":
                    OnAIAssist(null, null);
                    break;
                case "Enterprise":
                    OnEnterpriseManagement(null, null);
                    break;
                case "Budget":
                    OnBudgetAnalysis(null, null);
                    break;
                case "About":
                    OnAbout(null, null);
                    break;
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to handle keyboard shortcut for {Action}", action);
        }
    }

    /// <summary>
    /// Handles Azure AD sign in
    /// </summary>
    private async void OnSignIn(object sender, RoutedEventArgs e)
    {
        try
        {
            var signInButton = FindName("BtnSignIn") as dynamic;
            if (signInButton != null) signInButton.IsEnabled = false;
            var result = await _authService.SignInAsync();

            MessageBox.Show($"Successfully signed in as {result.Account.Username}",
                          "Sign In Successful",
                          MessageBoxButton.OK,
                          MessageBoxImage.Information);

            UpdateAuthenticationUI();
        }
        catch (AuthenticationException ex)
        {
            MessageBox.Show($"Sign in failed: {ex.Message}",
                          "Sign In Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Unexpected error during sign in: {ex.Message}",
                          "Sign In Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        finally
        {
            var signInButton = FindName("BtnSignIn") as dynamic;
            if (signInButton != null) signInButton.IsEnabled = true;
        }
    }

    /// <summary>
    /// Handles Azure AD sign out
    /// </summary>
    private async void OnSignOut(object sender, RoutedEventArgs e)
    {
        try
        {
            var signOutButton = FindName("BtnSignOut") as dynamic;
            if (signOutButton != null) signOutButton.IsEnabled = false;
            await _authService.SignOutAsync();

            MessageBox.Show("Successfully signed out",
                          "Sign Out Successful",
                          MessageBoxButton.OK,
                          MessageBoxImage.Information);

            UpdateAuthenticationUI();
        }
        catch (AuthenticationException ex)
        {
            MessageBox.Show($"Sign out failed: {ex.Message}",
                          "Sign Out Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Unexpected error during sign out: {ex.Message}",
                          "Sign Out Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        finally
        {
            var signOutButton = FindName("BtnSignOut") as dynamic;
            if (signOutButton != null) signOutButton.IsEnabled = true;
        }
    }

    /// <summary>
    /// Updates the authentication UI based on current authentication state
    /// </summary>
    private void UpdateAuthenticationUI()
    {
        if (_authService == null)
        {
            // DI not initialized; avoid NRE during early failure paths
            return;
        }

        if (_authService.IsAuthenticated)
        {
            var signInButton = FindName("BtnSignIn") as dynamic;
            if (signInButton != null) signInButton.IsEnabled = false;
            var signOutButton = FindName("BtnSignOut") as dynamic;
            if (signOutButton != null) signOutButton.IsEnabled = true;

            // Update the view model with current user info
            var viewModel = DataContext as ViewModels.MainViewModel;
            if (viewModel != null)
            {
                var userInfo = _authService.GetUserInfo();
                viewModel.CurrentUserName = userInfo.Name;
            }
        }
        else
        {
            var signInButton = FindName("BtnSignIn") as dynamic;
            if (signInButton != null) signInButton.IsEnabled = true;
            var signOutButton = FindName("BtnSignOut") as dynamic;
            if (signOutButton != null) signOutButton.IsEnabled = false;

            // Update the view model
            var viewModel = DataContext as ViewModels.MainViewModel;
            if (viewModel != null)
            {
                viewModel.CurrentUserName = "Not signed in";
            }
        }
    }

    /// <summary>
    /// Handles authentication state changes
    /// </summary>
    private void OnAuthenticationStateChanged(object sender, AuthenticationEventArgs e)
    {
        // Update UI on UI thread
        Dispatcher.Invoke(() => UpdateAuthenticationUI());
    }
}
