using System.Windows;
using System.Windows.Input;
using Syncfusion.SfSkinManager; // Theme manager
using Syncfusion.Windows.Shared; // Theme names (if needed)
using Syncfusion.UI.Xaml.Grid; // Grid controls
using Syncfusion.Windows.Tools.Controls; // Ribbon controls
using WileyWidget.Services;
using Serilog;
using System.Linq;
using Microsoft.Extensions.DependencyInjection;
using WileyWidget.ViewModels;
using System;
using System.Reflection;
using WileyWidget.Attributes;
using System.Diagnostics;
using System.Collections.Generic;
using System.Windows.Data;
using System.Windows.Media.Animation;
using System.Collections.Concurrent;

namespace WileyWidget;

/// <summary>
/// Primary shell window: applies persisted theme + window geometry, wires basic commands (theme switch, about),
/// and persists size/state on close. Keeps logic minimal—heavy operations belong in view models/services.
/// </summary>
public partial class MainWindow : Window
{
    // Grid control field (automatically generated by WPF from XAML x:Name)
    // private Syncfusion.UI.Xaml.Grid.SfDataGrid Grid;

    // Ribbon button fields (automatically generated by WPF from XAML x:Name)
    // private dynamic BtnFluentDark;
    // private dynamic BtnFluentLight;
    // private dynamic BtnDynamicColumns;

    private readonly AuthenticationService _authService;
    private readonly IServiceProvider _serviceProvider;
    private IServiceScope _viewScope; // keep scoped services alive for the window lifetime
    // Cache Enterprise property metadata to avoid repeated reflection when building dynamic columns
    private static readonly ConcurrentDictionary<Type, (PropertyInfo Prop, WileyWidget.Attributes.GridDisplayAttribute Attr)[]> _columnPropertyCache = new();

    private Syncfusion.UI.Xaml.Grid.SfDataGrid GetDataGrid()
    {
        return FindName("Grid") as Syncfusion.UI.Xaml.Grid.SfDataGrid;
    }

    // Keep a parameterless constructor for XAML/designer and legacy call sites
    public MainWindow()
    {
        var constructorTimer = Stopwatch.StartNew();
        App.LogDebugEvent("VIEW_INIT", "MainWindow constructor started");

        InitializeComponent();

        // Try to resolve services from the global provider when available. If not available
        // we'll continue and let UpdateAuthenticationUI be defensive.
        try
        {
            var provider = App.ServiceProvider;
            if (provider == null && Application.Current?.Properties?.Contains("ServiceProvider") == true)
            {
                provider = Application.Current.Properties["ServiceProvider"] as System.IServiceProvider;
            }

            _serviceProvider = provider;

            if (_serviceProvider != null)
            {
                try
                {
                    _authService = _serviceProvider.GetService<AuthenticationService>();
                    if (_authService != null)
                    {
                        _authService.AuthenticationStateChanged += OnAuthenticationStateChanged;
                    }
                }
                catch (Exception innerEx)
                {
                    Log.Warning(innerEx, "Failed to resolve AuthenticationService from DI container during MainWindow construction");
                }
            }

            App.LogDebugEvent("VIEW_INIT", $"MainWindow services initialized in {constructorTimer.ElapsedMilliseconds}ms");
        }
        catch (Exception ex)
        {
            // Keep the constructor from crashing - log and continue; UpdateAuthenticationUI will be defensive
            Log.Error(ex, "Unexpected error during MainWindow construction service resolution");
        }

        // Apply persisted theme or default
        TryApplyTheme(SettingsService.Instance.Current.Theme);
        // Dynamic columns will be built when DataContext is set in OnWindowLoaded
        RestoreWindowState();
        Loaded += OnWindowLoaded;
        Closing += (_, _) => PersistWindowState();
        KeyDown += OnKeyDown;
        UpdateThemeToggleVisuals();

        constructorTimer.Stop();
        App.LogDebugEvent("VIEW_INIT", $"MainWindow constructor completed in {constructorTimer.ElapsedMilliseconds}ms");
        App.LogStartupTiming("MainWindow Constructor", constructorTimer.Elapsed);
    }

    private async void OnWindowLoaded(object sender, RoutedEventArgs e)
    {
        var loadTimer = Stopwatch.StartNew();
        App.LogDebugEvent("VIEW_INIT", "MainWindow.OnWindowLoaded started");

        // Initialize DataContext with scoped services when window is loaded
        try
        {
            App.LogDebugEvent("VIEW_INIT", "Creating service scope and ViewModel");
            _viewScope = _serviceProvider.CreateScope();
            var mainViewModel = _viewScope.ServiceProvider.GetRequiredService<ViewModels.MainViewModel>();
            DataContext = mainViewModel;

            App.LogDebugEvent("VIEW_INIT", "DataContext set, configuring ViewModel properties");

            // Subscribe to property changes to handle dynamic column toggling
            mainViewModel.PropertyChanged += OnViewModelPropertyChanged;
            
            // Load and apply the persisted column mode preference
            mainViewModel.UseDynamicColumns = SettingsService.Instance.Current.UseDynamicColumns;

            // Now that DataContext and visual tree are ready, apply maximized state and auth UI
            App.LogDebugEvent("VIEW_INIT", "Applying window state and authentication UI");
            ApplyMaximized();
            await UpdateAuthenticationUIAsyncInternal();
            
            // Initialize grid columns based on current setting
            var grid = GetDataGrid();
            if (grid != null)
            {
                App.LogDebugEvent("VIEW_INIT", "Initializing grid columns");
                if (mainViewModel.UseDynamicColumns)
                {
                    BuildDynamicColumns();
                    App.LogDebugEvent("VIEW_INIT", "Dynamic columns built");
                }
                else
                {
                    grid.AutoGenerateColumns = false;
                    grid.Columns.Clear();
                    AddStaticColumns(grid);
                    App.LogDebugEvent("VIEW_INIT", "Static columns added");
                }
            }

            loadTimer.Stop();
            App.LogDebugEvent("VIEW_INIT", $"MainWindow.OnWindowLoaded completed in {loadTimer.ElapsedMilliseconds}ms");
            App.LogStartupTiming("MainWindow OnWindowLoaded", loadTimer.Elapsed);
            Log.Information("MainWindow loaded and initialized successfully");
        }
        catch (Exception ex)
        {
            App.LogDebugEvent("VIEW_INIT_ERROR", $"MainWindow.OnWindowLoaded failed: {ex.Message}");
            Log.Error(ex, "Failed to initialize MainViewModel");
            MessageBox.Show($"Failed to initialize main view: {ex.Message}", "Initialization Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }

        // Dispose scope and unsubscribe events when the window is closing
        this.Closing += (_, _) =>
        {
            try
            {
                _authService.AuthenticationStateChanged -= OnAuthenticationStateChanged;
            }
            catch { /* ignore */ }
            try
            {
                if (DataContext is ViewModels.MainViewModel vm)
                {
                    vm.PropertyChanged -= OnViewModelPropertyChanged;
                }
            }
            catch { /* ignore */ }
            try
            {
                _viewScope?.Dispose();
                _viewScope = null;
            }
            catch { /* ignore */ }
        };

        // Additional safety in case Closing isn't invoked
        this.Closed += (_, _) =>
        {
            try { if (_authService != null) _authService.AuthenticationStateChanged -= OnAuthenticationStateChanged; } catch { }
            try { if (DataContext is ViewModels.MainViewModel vm) vm.PropertyChanged -= OnViewModelPropertyChanged; } catch { }
            try { _viewScope?.Dispose(); _viewScope = null; } catch { }
        };
    }

    private void OnViewModelPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(ViewModels.MainViewModel.UseDynamicColumns))
        {
            var vm = DataContext as ViewModels.MainViewModel;
            var grid = GetDataGrid();
            if (grid == null) return;

            // Persist the column mode preference
            SettingsService.Instance.Current.UseDynamicColumns = vm?.UseDynamicColumns ?? false;
            SettingsService.Instance.Save();

            if (vm?.UseDynamicColumns == true)
            {
                BuildDynamicColumns();
            }
            else
            {
                // Switch back to static columns defined in XAML
                grid.AutoGenerateColumns = false;
                grid.Columns.Clear();
                
                // Re-add the static columns
                AddStaticColumns(grid);
            }
        }
    }

    private void AddStaticColumns(Syncfusion.UI.Xaml.Grid.SfDataGrid grid)
    {
        // Add the static columns back - unified set based on Enterprise model
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridTextColumn { HeaderText = "Id", MappingName = "Id", Width = 60 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridTextColumn { HeaderText = "Name", MappingName = "Name", Width = 150 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridTextColumn { HeaderText = "Type", MappingName = "Type", Width = 100 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Current Rate", MappingName = "CurrentRate", NumberDecimalDigits = 2, Width = 100 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Citizens Served", MappingName = "CitizenCount", NumberDecimalDigits = 0, Width = 120 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Monthly Expenses", MappingName = "MonthlyExpenses", NumberDecimalDigits = 2, Width = 130 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Annual Budget", MappingName = "TotalBudget", NumberDecimalDigits = 2, Width = 120 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Monthly Revenue", MappingName = "MonthlyRevenue", NumberDecimalDigits = 2, Width = 130 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridNumericColumn { HeaderText = "Monthly Balance", MappingName = "MonthlyBalance", NumberDecimalDigits = 2, Width = 120 });
        grid.Columns.Add(new Syncfusion.UI.Xaml.Grid.GridTextColumn { HeaderText = "Notes", MappingName = "Notes", Width = 200 });
    }

    /// <summary>
    /// Dynamically builds columns for each public property of the Enterprise model when enabled.
    /// Supports different column types based on property types and includes proper formatting.
    /// </summary>
    private void BuildDynamicColumns()
    {
        try
        {
            var vm = DataContext as ViewModels.MainViewModel;
            var grid = GetDataGrid();
            if (grid == null) return;

            grid.AutoGenerateColumns = false;
            grid.Columns.Clear();

            // Get the Enterprise type to build columns from its properties (cached)
            var enterpriseType = typeof(WileyWidget.Models.Enterprise);
            var properties = _columnPropertyCache.GetOrAdd(enterpriseType, t =>
            {
                return t.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                    .Where(p => p.CanRead && !p.GetGetMethod().IsVirtual) // Exclude navigation/navigation-like
                    .Select(p => (
                        Prop: p,
                        Attr: p.GetCustomAttribute(typeof(WileyWidget.Attributes.GridDisplayAttribute)) as WileyWidget.Attributes.GridDisplayAttribute
                    ))
                    .Where(x => x.Attr?.Visible != false) // Exclude properties marked as not visible
                    .OrderBy(x => x.Attr?.Order ?? 50)
                    .ToArray();
            });

            var hadPropertyErrors = false;
            foreach (var entry in properties)
            {
                try
                {
                    var prop = entry.Prop;
                    var displayAttr = entry.Attr;
                    var mappingName = prop.Name;
                    var headerText = displayAttr?.HeaderText ?? SplitCamelCase(prop.Name);

                    // Create appropriate column type based on property type
                    var column = CreateColumnForProperty(prop, mappingName, headerText, displayAttr);
                    if (column != null)
                    {
                        grid.Columns.Add(column);
                    }
                }
                catch (Exception propEx)
                {
                    hadPropertyErrors = true;
                    Log.Warning(propEx, "Dynamic column creation failed for property {Property}", entry.Prop?.Name);
                }
            }

            if (hadPropertyErrors)
            {
                Log.Warning("One or more properties failed to generate dynamic columns; remaining columns were loaded");
            }

            Log.Information("Dynamic columns built successfully for {TypeName} with {ColumnCount} columns", 
                           enterpriseType.Name, grid.Columns.Count);
        }
        catch (Exception ex)
        {
            ErrorReportingService.Instance.ReportError(ex, "Grid_BuildDynamicColumns", showToUser: false);
            
            // Fallback to static columns with user notification
            var grid = GetDataGrid();
            if (grid != null) 
            {
                grid.AutoGenerateColumns = false;
                grid.Columns.Clear();
                AddStaticColumns(grid);
                Log.Warning("Fallback to static columns due to dynamic column build failure");
                
                // Show user-friendly message
                MessageBox.Show(
                    "Unable to display custom column layout. Using default column layout instead.\n\n" +
                    "Some advanced features may not be available.",
                    "Column Layout Fallback",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
        }
    }



    /// <summary>
    /// Creates the appropriate Syncfusion column type based on the property type
    /// </summary>
    private Syncfusion.UI.Xaml.Grid.GridColumn CreateColumnForProperty(System.Reflection.PropertyInfo prop, string mappingName, string headerText, WileyWidget.Attributes.GridDisplayAttribute displayAttr = null)
    {
        var propType = prop.PropertyType;

        // Handle nullable types
        var underlyingType = Nullable.GetUnderlyingType(propType) ?? propType;

        // Skip complex types that aren't suitable for columns
        if (underlyingType.IsClass && underlyingType != typeof(string))
        {
            return null; // Skip navigation properties and complex objects
        }

        // Handle enums using a ComboBox column
        if (underlyingType.IsEnum)
        {
            try
            {
                return new GridComboBoxColumn
                {
                    MappingName = mappingName,
                    HeaderText = headerText,
                    ItemsSource = Enum.GetValues(underlyingType),
                    Width = displayAttr?.Width ?? 120,
                    AllowSorting = true,
                    AllowFiltering = true
                };
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Failed to create enum ComboBox column for {Property}", mappingName);
            }
        }

        if (underlyingType == typeof(int) || underlyingType == typeof(long) ||
            underlyingType == typeof(short) || underlyingType == typeof(byte))
        {
            return new GridNumericColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                NumberDecimalDigits = displayAttr?.DecimalDigits >= 0 ? displayAttr.DecimalDigits : 0,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true
            };
        }
        else if (underlyingType == typeof(decimal))
        {
            return new GridNumericColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                NumberDecimalDigits = displayAttr?.DecimalDigits >= 0 ? displayAttr.DecimalDigits : 2,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true
            };
        }
        else if (underlyingType == typeof(double) || underlyingType == typeof(float))
        {
            return new GridNumericColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                NumberDecimalDigits = displayAttr?.DecimalDigits ?? 2,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true
            };
        }
        else if (underlyingType == typeof(DateTime))
        {
            return new GridDateTimeColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true
            };
        }
        else if (underlyingType == typeof(bool))
        {
            return new GridCheckBoxColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true
            };
        }
        else
        {
            // Default to text column for strings and other types
            var col = new GridTextColumn
            {
                MappingName = mappingName,
                HeaderText = headerText,
                Width = displayAttr?.Width ?? 120,
                AllowSorting = true,
                AllowFiltering = true,
                AllowEditing = mappingName != "Id" // Don't allow editing ID column
            };

            // Apply converter if specified on attribute
            if (displayAttr != null && (displayAttr.ConverterType != null || !string.IsNullOrWhiteSpace(displayAttr.ConverterResourceKey)))
            {
                try
                {
                    var binding = new Binding(mappingName) { Mode = BindingMode.TwoWay };
                    if (!string.IsNullOrWhiteSpace(displayAttr.ConverterResourceKey))
                    {
                        var converterObj = TryFindResource(displayAttr.ConverterResourceKey);
                        if (converterObj is IValueConverter resConv)
                        {
                            binding.Converter = resConv;
                        }
                    }
                    else if (displayAttr.ConverterType != null)
                    {
                        if (Activator.CreateInstance(displayAttr.ConverterType) is IValueConverter conv)
                        {
                            binding.Converter = conv;
                        }
                    }

                    // GridTextColumn supports ValueBinding
                    col.ValueBinding = binding;
                }
                catch (Exception convEx)
                {
                    Log.Warning(convEx, "Failed to apply converter for column {MappingName}", mappingName);
                }
            }
            return col;
        }
    }



    /// <summary>
    /// Converts camelCase or PascalCase to readable text with spaces
    /// </summary>
    private string SplitCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;

        var result = System.Text.RegularExpressions.Regex.Replace(input, "([a-z])([A-Z])", "$1 $2");
        return result;
    }

    /// <summary>
    /// Copy selected items from the data grid to clipboard
    /// </summary>
    private void OnCopy(object sender, RoutedEventArgs e)
    {
        try
        {
            var grid = GetDataGrid();
            if (grid == null || grid.SelectedItems == null || grid.SelectedItems.Count == 0)
            {
                MessageBox.Show("Please select one or more items to copy.",
                              "No Selection",
                              MessageBoxButton.OK,
                              MessageBoxImage.Information);
                return;
            }

            var selectedItems = grid.SelectedItems;
            var stringBuilder = new System.Text.StringBuilder();

            // Add header row
            if (selectedItems.Count > 0 && selectedItems[0] != null)
            {
                var type = selectedItems[0].GetType();
                var properties = type.GetProperties()
                    .Where(p => p.CanRead)
                    .Select(p => SplitCamelCase(p.Name))
                    .ToArray();

                stringBuilder.AppendLine(string.Join("\t", properties));
            }

            // Add data rows
            foreach (var item in selectedItems)
            {
                if (item == null) continue;

                var type = item.GetType();
                var values = type.GetProperties()
                    .Where(p => p.CanRead)
                    .Select(p =>
                    {
                        try
                        {
                            var value = p.GetValue(item);
                            return value?.ToString() ?? "";
                        }
                        catch
                        {
                            return "";
                        }
                    })
                    .ToArray();

                stringBuilder.AppendLine(string.Join("\t", values));
            }

            Clipboard.SetText(stringBuilder.ToString());
            Log.Information("Copied {Count} items to clipboard", selectedItems.Count);
        }
        catch (Exception ex)
        {
            ErrorReportingService.Instance.ReportError(ex, "Grid_OnCopy", showToUser: true);
        }
    }

    /// <summary>
    /// Paste items from clipboard to the data grid
    /// </summary>
    private void OnPaste(object sender, RoutedEventArgs e)
    {
        // Check role-based access: only admins can paste
        var viewModel = DataContext as ViewModels.MainViewModel;
        if (viewModel == null || !viewModel.IsUserAdmin)
        {
            MessageBox.Show("Paste operation is restricted to administrators only.",
                          "Access Denied",
                          MessageBoxButton.OK,
                          MessageBoxImage.Warning);
            return;
        }

        try
        {
            ErrorReportingService.Instance.TrackEvent("GridPasteStarted");
            // show busy cursor for large pastes
            Mouse.OverrideCursor = Cursors.Wait;
            if (!Clipboard.ContainsText())
            {
                MessageBox.Show("Clipboard does not contain text data.",
                              "No Text Data",
                              MessageBoxButton.OK,
                              MessageBoxImage.Information);
                return;
            }

            var clipboardText = Clipboard.GetText();
            var lines = clipboardText.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.RemoveEmptyEntries);

            if (lines.Length < 2) // Need at least header + 1 data row
            {
                MessageBox.Show("Clipboard data must contain headers and at least one data row.",
                              "Invalid Format",
                              MessageBoxButton.OK,
                              MessageBoxImage.Warning);
                return;
            }

            var vm = DataContext as ViewModels.MainViewModel;
            if (vm == null) return;

            // Parse header to understand column mapping
            var headers = lines[0].Split('\t').Select(h => h.Trim()).ToArray();
            var pastedCount = 0;
            var skippedCount = 0;
            var rowErrors = 0;

            // Create new items from data rows
            for (int i = 1; i < lines.Length; i++)
            {
                var values = lines[i].Split('\t').Select(v => v.Trim()).ToArray();

                // Skip malformed rows
                if (values.Length != headers.Length)
                {
                    Log.Warning("Skipping row {Row}: expected {Expected} columns, got {Actual}", i + 1, headers.Length, values.Length);
                    skippedCount++;
                    continue;
                }

                try
                {
                    // Create header-value mapping for this row
                    var headerValueMap = new Dictionary<string, string>();
                    for (int j = 0; j < headers.Length; j++)
                    {
                        if (!string.IsNullOrWhiteSpace(headers[j]) && !string.IsNullOrWhiteSpace(values[j]))
                        {
                            headerValueMap[headers[j]] = values[j];
                        }
                    }

                    // Skip rows with no valid data
                    if (headerValueMap.Count == 0)
                    {
                        Log.Warning("Skipping row {Row}: no valid data found", i + 1);
                        skippedCount++;
                        continue;
                    }

                    // Create new Enterprise instance using repository mapping
                    var newEnterprise = vm.CreateEnterpriseFromHeaderMapping(headerValueMap);

                    // Best-effort recovery for culture-specific numbers or formatting issues
                    if (newEnterprise.CurrentRate == 0 && TryGetHeaderValue(headerValueMap, out var rateRaw, "currentrate", "rate", "current rate", "monthly rate"))
                    {
                        if (TryParseDecimal(rateRaw, out var rateParsed)) newEnterprise.CurrentRate = rateParsed;
                    }
                    if (newEnterprise.MonthlyExpenses == 0 && TryGetHeaderValue(headerValueMap, out var expRaw, "monthlyexpenses", "expenses", "operating expenses", "monthly expenses"))
                    {
                        if (TryParseDecimal(expRaw, out var expParsed)) newEnterprise.MonthlyExpenses = expParsed;
                    }
                    if (newEnterprise.TotalBudget == 0 && TryGetHeaderValue(headerValueMap, out var budgetRaw, "totalbudget", "budget", "allocated budget"))
                    {
                        if (TryParseDecimal(budgetRaw, out var budgetParsed)) newEnterprise.TotalBudget = budgetParsed;
                    }
                    if (newEnterprise.CitizenCount == 0 && TryGetHeaderValue(headerValueMap, out var countRaw, "citizencount", "citizens", "population", "customer count"))
                    {
                        if (TryParseInt(countRaw, out var countParsed)) newEnterprise.CitizenCount = countParsed;
                    }

                    // Set default values for required properties if not provided
                    if (string.IsNullOrWhiteSpace(newEnterprise.Name))
                        newEnterprise.Name = $"Imported Enterprise {vm.Enterprises.Count + 1}";
                    if (string.IsNullOrWhiteSpace(newEnterprise.Type))
                        newEnterprise.Type = "Utility";

                    // Only set defaults for numeric fields if they weren't explicitly provided
                    // (0 might be a valid value from the data)
                    if (newEnterprise.CurrentRate == 0 && !WasFieldProvided(headerValueMap, "currentrate", "rate", "current rate"))
                        newEnterprise.CurrentRate = 25.00M;
                    if (newEnterprise.MonthlyExpenses == 0 && !WasFieldProvided(headerValueMap, "monthlyexpenses", "expenses", "monthly expenses"))
                        newEnterprise.MonthlyExpenses = 1000.00M;
                    if (newEnterprise.CitizenCount == 0 && !WasFieldProvided(headerValueMap, "citizencount", "citizens", "count", "citizen count"))
                        newEnterprise.CitizenCount = 100;

                    // Generate unique ID (ignore any pasted ID to avoid collisions)
                    var nextId = vm.Enterprises.Count == 0 ? 1 : vm.Enterprises.Max(e => e.Id) + 1;
                    newEnterprise.Id = nextId;

                    // Ensure name uniqueness if duplicates exist
                    if (!string.IsNullOrWhiteSpace(newEnterprise.Name) &&
                        vm.Enterprises.Any(e => string.Equals(e.Name, newEnterprise.Name, StringComparison.OrdinalIgnoreCase)))
                    {
                        newEnterprise.Name = GenerateUniqueName(vm, newEnterprise.Name);
                    }

                    // Add to collection
                    vm.Enterprises.Add(newEnterprise);
                    pastedCount++;
                }
                catch (Exception ex)
                {
                    Log.Warning(ex, "Failed to create enterprise from clipboard row {Row}", i + 1);
                    skippedCount++;
                    rowErrors++;
                    // Centralize row-specific error logging
                    ErrorReportingService.Instance.ReportError(ex, "Grid_OnPaste_Row", showToUser: false);
                }
            }

            // Show results to user (brief toast-like status)
            var message = $"Successfully pasted {pastedCount} enterprise(s).";
            if (skippedCount > 0)
                message += $" {skippedCount} row(s) were skipped due to errors.";

            // Prefer non-blocking brief notification: update StatusBar text if present
            try
            {
                var statusText = this.FindName("StatusTextBlock") as System.Windows.Controls.TextBlock;
                if (statusText != null)
                {
                    statusText.Text = message;
                    var fade = new DoubleAnimation(1.0, 0.6, new Duration(TimeSpan.FromSeconds(3)));
                    statusText.BeginAnimation(System.Windows.UIElement.OpacityProperty, fade);
                }
                else
                {
                    // Fallback to dialog
                    MessageBox.Show(message, "Paste Complete",
                        MessageBoxButton.OK,
                        pastedCount > 0 ? MessageBoxImage.Information : MessageBoxImage.Warning);
                }
            }
            catch
            {
                MessageBox.Show(message, "Paste Complete",
                    MessageBoxButton.OK,
                    pastedCount > 0 ? MessageBoxImage.Information : MessageBoxImage.Warning);
            }

            Log.Information("Pasted {PastedCount} items from clipboard, skipped {SkippedCount}", pastedCount, skippedCount);
            ErrorReportingService.Instance.TrackEvent("GridPasteCompleted", new Dictionary<string, object>
            {
                ["RowsPasted"] = pastedCount,
                ["RowsSkipped"] = skippedCount,
                ["RowErrors"] = rowErrors,
                ["HeaderCount"] = headers.Length
            });
            ErrorReportingService.Instance.IncrementCounter("GridPaste.TotalRows", pastedCount + skippedCount);
            if (rowErrors > 0) ErrorReportingService.Instance.IncrementCounter("GridPaste.RowErrors", rowErrors);
        }
        catch (Exception ex)
        {
            ErrorReportingService.Instance.ReportError(ex, "Grid_OnPaste", showToUser: true);
            ErrorReportingService.Instance.TrackEvent("GridPasteFailed", new Dictionary<string, object>
            {
                ["Message"] = ex.Message
            });
        }
        finally
        {
            Mouse.OverrideCursor = null;
        }
    }

    private bool TryGetHeaderValue(IDictionary<string, string> headerValueMap, out string value, params string[] fieldNames)
    {
        value = null;
        foreach (var kvp in headerValueMap)
        {
            var normalizedHeader = kvp.Key.Replace(" ", string.Empty).Replace("-", string.Empty).Replace("_", string.Empty).ToLowerInvariant();
            if (fieldNames.Any(field => normalizedHeader.Contains(field.Replace(" ", string.Empty).ToLowerInvariant())))
            {
                value = kvp.Value;
                return true;
            }
        }
        return false;
    }

    private bool TryParseInt(string value, out int result)
    {
        var clean = value?.Replace(",", string.Empty)?.Trim();
        return int.TryParse(clean, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.CurrentCulture, out result);
    }

    private string GenerateUniqueName(ViewModels.MainViewModel vm, string baseName)
    {
        var suffix = 1;
        var candidate = baseName;
        while (vm.Enterprises.Any(e => string.Equals(e.Name, candidate, StringComparison.OrdinalIgnoreCase)))
        {
            suffix++;
            candidate = $"{baseName} ({suffix})";
        }
        return candidate;
    }

    /// <summary>
    /// Helper method to parse decimal values, handling currency symbols and formatting
    /// </summary>
    private bool TryParseDecimal(string value, out decimal result)
    {
        // Remove common currency symbols and formatting
        var cleanValue = value.Replace("$", "").Replace(",", "").Replace(" ", "").Trim();

        // Try parsing with various number styles
        return decimal.TryParse(cleanValue,
            System.Globalization.NumberStyles.Number |
            System.Globalization.NumberStyles.Currency |
            System.Globalization.NumberStyles.AllowDecimalPoint,
            System.Globalization.CultureInfo.CurrentCulture,
            out result);
    }

    /// <summary>
    /// Helper method to check if a field was provided in the header-value mapping
    /// </summary>
    private bool WasFieldProvided(IDictionary<string, string> headerValueMap, params string[] fieldNames)
    {
        foreach (var kvp in headerValueMap)
        {
            var normalizedHeader = kvp.Key.Replace(" ", "").Replace("-", "").Replace("_", "").ToLowerInvariant();
            if (fieldNames.Any(field => normalizedHeader.Contains(field.ToLowerInvariant())))
            {
                return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Helper method to check if a field was provided in the data (not empty)
    /// </summary>
    private bool WasFieldProvided(string[] headers, string[] values, params string[] fieldNames)
    {
        for (int i = 0; i < headers.Length; i++)
        {
            var normalizedHeader = headers[i].Replace(" ", "").Replace("-", "").Replace("_", "").ToLowerInvariant();
            if (fieldNames.Any(field => normalizedHeader.Contains(field.ToLowerInvariant())))
            {
                if (!string.IsNullOrWhiteSpace(values[i]))
                    return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Attempt to apply a Syncfusion theme; falls back to Fluent Light if requested theme fails (e.g., renamed or removed).
    /// </summary>
    private void TryApplyTheme(string themeName)
    {
        ThemeUtility.TryApplyTheme(this, themeName);
    }



    /// <summary>Switch to Fluent Dark theme and persist choice.</summary>
    private void OnFluentDark(object sender, RoutedEventArgs e)
    {
    TryApplyTheme("FluentDark");
    SettingsService.Instance.Current.Theme = "FluentDark";
        SettingsService.Instance.Save();
    Log.Information("Theme changed to {Theme}", "Fluent Dark");
    UpdateThemeToggleVisuals();
        // transient status
        var statusText = this.FindName("StatusTextBlock") as System.Windows.Controls.TextBlock;
        if (statusText != null) statusText.Text = "Theme: Fluent Dark";
    }
    /// <summary>Switch to Fluent Light theme and persist choice.</summary>
    private void OnFluentLight(object sender, RoutedEventArgs e)
    {
    TryApplyTheme("FluentLight");
    SettingsService.Instance.Current.Theme = "FluentLight";
        SettingsService.Instance.Save();
    Log.Information("Theme changed to {Theme}", "Fluent Light");
        UpdateThemeToggleVisuals();
        // transient status
        var statusText = this.FindName("StatusTextBlock") as System.Windows.Controls.TextBlock;
        if (statusText != null) statusText.Text = "Theme: Fluent Light";
    }

    private void UpdateThemeToggleVisuals()
    {
        var current = Services.ThemeUtility.NormalizeTheme(SettingsService.Instance.Current.Theme);
        RibbonButton btnDark = FindName("BtnFluentDark") as RibbonButton;
        if (btnDark != null)
        {
            btnDark.IsEnabled = current != "FluentDark";
            btnDark.Label = current == "FluentDark" ? "✔ Fluent Dark" : "Fluent Dark";
        }
        RibbonButton btnLight = FindName("BtnFluentLight") as RibbonButton;
        if (btnLight != null)
        {
            btnLight.IsEnabled = current != "FluentLight";
            btnLight.Label = current == "FluentLight" ? "✔ Fluent Light" : "Fluent Light";
        }
    }
    /// <summary>Display modal About dialog with version information.</summary>
    private void OnAbout(object sender, RoutedEventArgs e)
    {
        var about = new AboutWindow { Owner = this };
        about.ShowDialog();
    }

    /// <summary>
    /// Restores last known window bounds (only if previously saved). Maximized state is applied after window is loaded
    /// to avoid layout measurement issues during construction.
    /// </summary>
    private void RestoreWindowState()
    {
        var s = SettingsService.Instance.Current;
        if (s.WindowWidth.HasValue) Width = s.WindowWidth.Value;
        if (s.WindowHeight.HasValue) Height = s.WindowHeight.Value;
        if (s.WindowLeft.HasValue) Left = s.WindowLeft.Value;
        if (s.WindowTop.HasValue) Top = s.WindowTop.Value;
    }

    /// <summary>
    /// Applies persisted maximized state post-load. Separated for clarity and potential future animation hooks.
    /// </summary>
    private void ApplyMaximized()
    {
        var s = SettingsService.Instance.Current;
        if (s.WindowMaximized == true)
            WindowState = WindowState.Maximized;
    }

    /// <summary>
    /// Persists window bounds only when in Normal state to avoid capturing the restored size of a maximized window.
    /// </summary>
    private void PersistWindowState()
    {
        var s = SettingsService.Instance.Current;
        s.WindowMaximized = WindowState == WindowState.Maximized;
        if (WindowState == WindowState.Normal)
        {
            s.WindowWidth = Width;
            s.WindowHeight = Height;
            s.WindowLeft = Left;
            s.WindowTop = Top;
        }
        SettingsService.Instance.Save();
    }

    /// <summary>
    /// Opens the Enterprise Management panel
    /// </summary>
    private void OnEnterpriseManagement(object sender, RoutedEventArgs e)
    {
        try
        {
            ActivateDockingPanel("EnterprisePanel");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Enterprise Management: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Budget Analysis panel
    /// </summary>
    private void OnBudgetAnalysis(object sender, RoutedEventArgs e)
    {
        try
        {
            ActivateDockingPanel("BudgetPanel");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Budget Analysis: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Customer Management window
    /// </summary>
    private void OnCustomerManagement(object sender, RoutedEventArgs e)
    {
        try
        {
            UtilityCustomerView.ShowCustomerWindow();
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Customer Management: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    private void OnToggleDynamicColumns(object sender, RoutedEventArgs e)
    {
        try
        {
            var grid = GetDataGrid();
            if (grid == null) return;
            
            // Toggle the ViewModel property which will trigger the property changed event
            if (DataContext is ViewModels.MainViewModel vm)
            {
                vm.UseDynamicColumns = !vm.UseDynamicColumns;
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to toggle column mode");
            MessageBox.Show($"Failed to toggle column mode: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the AI Assistant panel
    /// </summary>
    private void OnAIAssist(object sender, RoutedEventArgs e)
    {
        try
        {
            ActivateDockingPanel("AIAssistPanel");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open AI Assistant: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Settings panel
    /// </summary>
    private void OnSettings(object sender, RoutedEventArgs e)
    {
        try
        {
            ActivateDockingPanel("SettingsPanel");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Settings: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Opens the Dashboard panel
    /// </summary>
    private void OnDashboard(object sender, RoutedEventArgs e)
    {
        try
        {
            ActivateDockingPanel("DashboardPanel");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to open Dashboard: {ex.Message}",
                          "Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Handles keyboard shortcuts by delegating to existing event handlers
    /// </summary>
    private void HandleKeyboardShortcut(string action)
    {
        try
        {
            switch (action)
            {
                case "Settings":
                    OnSettings(null, null);
                    break;
                case "Dashboard":
                    OnDashboard(null, null);
                    break;
                case "AIAssist":
                    OnAIAssist(null, null);
                    break;
                case "Enterprise":
                    OnEnterpriseManagement(null, null);
                    break;
                case "Budget":
                    OnBudgetAnalysis(null, null);
                    break;
                case "About":
                    OnAbout(null, null);
                    break;
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to handle keyboard shortcut for {Action}", action);
        }
    }

    /// <summary>
    /// Handles window-level keyboard shortcuts
    /// </summary>
    private void OnKeyDown(object sender, KeyEventArgs e)
    {
        // Only handle if Ctrl is pressed
        if ((Keyboard.Modifiers & ModifierKeys.Control) != ModifierKeys.Control)
            return;

        // Scope copy/paste to when focus is within the main SfDataGrid to avoid conflicts
        bool focusInMainGrid = false;
        try
        {
            var focused = Keyboard.FocusedElement as DependencyObject;
            var grid = GetDataGrid();
            if (focused != null && grid != null)
            {
                focusInMainGrid = IsAncestorOf(grid, focused);
            }
        }
        catch { /* best effort */ }

        string action = null;
        switch (e.Key)
        {
            case Key.V:
                if (focusInMainGrid)
                {
                    OnPaste(null, null);
                    e.Handled = true;
                    return;
                }
                break;
            case Key.C:
                if (focusInMainGrid)
                {
                    OnCopy(null, null);
                    e.Handled = true;
                    return;
                }
                break;
            case Key.S:
                if ((Keyboard.Modifiers & ModifierKeys.Shift) == ModifierKeys.Shift)
                    action = "Settings";
                break;
            case Key.D:
                if ((Keyboard.Modifiers & ModifierKeys.Shift) == ModifierKeys.Shift)
                    action = "Dashboard";
                else
                    action = "AIAssist";
                break;
            case Key.E:
                action = "Enterprise";
                break;
            case Key.B:
                action = "Budget";
                break;
            case Key.A:
                if ((Keyboard.Modifiers & ModifierKeys.Shift) == ModifierKeys.Shift)
                    action = "About";
                break;
        }

        if (action != null)
        {
            HandleKeyboardShortcut(action);
            e.Handled = true;
        }
    }

    /// <summary>
    /// Returns true if ancestor is an ancestor of element in either visual or logical tree
    /// </summary>
    private static bool IsAncestorOf(DependencyObject ancestor, DependencyObject element)
    {
        if (ancestor == null || element == null) return false;

        // Visual tree walk
        var current = element;
        for (int i = 0; i < 200 && current != null; i++)
        {
            if (ReferenceEquals(current, ancestor)) return true;
            current = System.Windows.Media.VisualTreeHelper.GetParent(current);
        }

        // Logical tree fallback
        current = element;
        for (int i = 0; i < 200 && current != null; i++)
        {
            if (ReferenceEquals(current, ancestor)) return true;
            current = System.Windows.LogicalTreeHelper.GetParent(current);
        }

        return false;
    }

    /// <summary>
    /// Handles Azure AD sign in
    /// </summary>
    private async void OnSignIn(object sender, RoutedEventArgs e)
    {
        try
        {
            var signInButton = FindName("BtnSignIn") as RibbonButton;
            if (signInButton != null) signInButton.IsEnabled = false;
            var result = await _authService.SignInAsync();

            MessageBox.Show($"Successfully signed in as {result.Account.Username}",
                          "Sign In Successful",
                          MessageBoxButton.OK,
                          MessageBoxImage.Information);

            await UpdateAuthenticationUIAsyncInternal();
        }
        catch (AuthenticationException ex)
        {
            MessageBox.Show($"Sign in failed: {ex.Message}",
                          "Sign In Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Unexpected error during sign in: {ex.Message}",
                          "Sign In Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        finally
        {
            var signInButton = FindName("BtnSignIn") as RibbonButton;
            if (signInButton != null) signInButton.IsEnabled = true;
        }
    }

    /// <summary>
    /// Handles Azure AD sign out
    /// </summary>
    private async void OnSignOut(object sender, RoutedEventArgs e)
    {
        try
        {
            var signOutButton = FindName("BtnSignOut") as RibbonButton;
            if (signOutButton != null) signOutButton.IsEnabled = false;
            await _authService.SignOutAsync();

            MessageBox.Show("Successfully signed out",
                          "Sign Out Successful",
                          MessageBoxButton.OK,
                          MessageBoxImage.Information);

            UpdateAuthenticationUI();
        }
        catch (AuthenticationException ex)
        {
            MessageBox.Show($"Sign out failed: {ex.Message}",
                          "Sign Out Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Unexpected error during sign out: {ex.Message}",
                          "Sign Out Error",
                          MessageBoxButton.OK,
                          MessageBoxImage.Error);
        }
        finally
        {
            var signOutButton = FindName("BtnSignOut") as dynamic;
            if (signOutButton != null) signOutButton.IsEnabled = true;
        }
    }

    /// <summary>
    /// Updates the authentication UI based on current authentication state
    /// </summary>
    private void UpdateAuthenticationUI()
    {
        // Ensure we're on the UI thread
        if (!Dispatcher.CheckAccess())
        {
            _ = Dispatcher.InvokeAsync(async () => await UpdateAuthenticationUIAsyncInternal());
            return;
        }

        // On UI thread: run async version but don't block
        _ = UpdateAuthenticationUIAsyncInternal();
    }

    private string TryExtractEmailFromUserInfo(UserInfo userInfo)
    {
        if (userInfo == null) return string.Empty;

        // Prefer explicit Email if available
        var email = userInfo.Email;
        if (!string.IsNullOrWhiteSpace(email) && email.Contains("@"))
            return email;

        // Fall back to username if it looks like an email
        var candidate = userInfo.Username;
        if (!string.IsNullOrWhiteSpace(candidate) && candidate.Contains("@"))
            return candidate;

        // As a last resort, attempt to detect an email-like token in Name
        if (!string.IsNullOrWhiteSpace(userInfo.Name) && userInfo.Name.Contains("@"))
            return userInfo.Name;

        return string.Empty;
    }

    /// <summary>
    /// Activates a dockable panel in the DockingManager
    /// </summary>
    private void ActivateDockingPanel(string panelName)
    {
        try
        {
            var dockingManager = FindName("MainDockingManager") as Syncfusion.Windows.Tools.Controls.DockingManager;
            if (dockingManager == null) return;

            // Find the content control by name
            var contentControl = FindName(panelName) as System.Windows.Controls.ContentControl;
            if (contentControl == null) return;

            // If already open, bring to front; else set as document
            try
            {
                dockingManager.ActiveWindow = contentControl;
            }
            catch
            {
                Syncfusion.Windows.Tools.Controls.DockingManager.SetState(contentControl, Syncfusion.Windows.Tools.Controls.DockState.Document);
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to activate docking panel {PanelName}", panelName);
        }
    }

    /// <summary>
    /// Handles authentication state changes
    /// </summary>
    private void OnAuthenticationStateChanged(object sender, AuthenticationEventArgs e)
    {
        // Update UI on UI thread asynchronously to avoid blocking
        _ = Dispatcher.InvokeAsync(async () => await UpdateAuthenticationUIAsyncInternal());
    }

    // Async version used internally to support awaited flows from sign in/out
    private async System.Threading.Tasks.Task UpdateAuthenticationUIAsyncInternal()
    {
        await System.Windows.Threading.Dispatcher.Yield(System.Windows.Threading.DispatcherPriority.Background);
        try
        {
            if (_authService == null)
            {
                Log.Debug("Authentication service is not available - skipping authentication UI update");
                if (DataContext is ViewModels.MainViewModel vmFallback)
                {
                    vmFallback.CurrentUserName = "Not signed in";
                    vmFallback.CurrentUserEmail = string.Empty;
                    vmFallback.IsUserAdmin = false;
                    vmFallback.UserRoles = new List<string>();
                }
                return;
            }

            if (_authService.IsAuthenticated)
            {
                var signInButton = FindName("BtnSignIn") as RibbonButton;
                if (signInButton != null) signInButton.IsEnabled = false;
                var signOutButton = FindName("BtnSignOut") as RibbonButton;
                if (signOutButton != null) signOutButton.IsEnabled = true;

                if (DataContext is ViewModels.MainViewModel viewModel)
                {
                    var userInfo = _authService.GetUserInfo();
                    if (userInfo != null)
                    {
                        viewModel.CurrentUserName = string.IsNullOrWhiteSpace(userInfo.Name) ? userInfo.Username ?? Environment.UserName : userInfo.Name;
                        viewModel.CurrentUserEmail = TryExtractEmailFromUserInfo(userInfo);
                        viewModel.IsUserAdmin = userInfo.IsAdmin;
                        viewModel.UserRoles = userInfo.Roles ?? new List<string>();
                    }
                    else
                    {
                        Log.Warning("AuthenticationService reported IsAuthenticated=true but GetUserInfo() returned null");
                        viewModel.CurrentUserName = Environment.UserName ?? "Signed in";
                        viewModel.CurrentUserEmail = string.Empty;
                        viewModel.IsUserAdmin = false;
                        viewModel.UserRoles = new List<string>();
                    }
                }
            }
            else
            {
                var signInButton = FindName("BtnSignIn") as RibbonButton;
                if (signInButton != null) signInButton.IsEnabled = true;
                var signOutButton = FindName("BtnSignOut") as RibbonButton;
                if (signOutButton != null) signOutButton.IsEnabled = false;

                if (DataContext is ViewModels.MainViewModel viewModel)
                {
                    viewModel.CurrentUserName = "Not signed in";
                    viewModel.CurrentUserEmail = string.Empty;
                    viewModel.IsUserAdmin = false;
                    viewModel.UserRoles = new List<string>();
                }
            }
        }
        catch (Exception ex)
        {
            ErrorReportingService.Instance.ReportError(ex, "UpdateAuthenticationUIAsync", showToUser: false);
            Log.Error(ex, "Unhandled exception while updating authentication UI (async)");
        }
    }

    /// <summary>
    /// Handles key down events in the AI message input
    /// </summary>
    private void OnAIMessageKeyDown(object sender, System.Windows.Input.KeyEventArgs e)
    {
        if (e.Key == System.Windows.Input.Key.Enter && (System.Windows.Input.Keyboard.Modifiers & System.Windows.Input.ModifierKeys.Shift) == 0)
        {
            // Send message on Enter (but allow Shift+Enter for new lines)
            if (DataContext is ViewModels.MainViewModel vm && vm.SendAIMessageCommand.CanExecute(null))
            {
                ActivateDockingPanel("AIAssistPanel");
                vm.SendAIMessageCommand.Execute(null);
                e.Handled = true;
            }
        }
    }
}
